name: deploy

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
    
jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.19.x]
    steps:
      - uses: actions/checkout@v3
        with:
          path: dist
